import React, { useState, useEffect } from 'react';
import { Card, CardHeader, CardContent, Button, TextArea, CopyButton, Select, Label } from '../components/ui/Shared';
import { TrashIcon } from '../components/ui/Icons';
import { useAppContext } from '../contexts/AppContext';

// --- JSON Tools Component ---
export const JsonTools: React.FC = () => {
  const [input, setInput] = useState('');
  const [output, setOutput] = useState('');
  const [mode, setMode] = useState('format');
  const [error, setError] = useState<string | null>(null);
  const { t } = useAppContext();

  useEffect(() => {
    if (!input.trim()) {
      setOutput('');
      setError(null);
      return;
    }
    try {
      const parsed = JSON.parse(input);
      setError(null);
      switch (mode) {
        case 'format': setOutput(JSON.stringify(parsed, null, 2)); break;
        case 'minify': setOutput(JSON.stringify(parsed)); break;
        case 'toTS': setOutput(jsonToTypeScript(parsed)); break;
        case 'toGo': setOutput(jsonToGo(parsed)); break;
        case 'toJava': setOutput(jsonToJava(parsed)); break;
        case 'toXML': setOutput(jsonToXml(parsed)); break;
        case 'toCSV': setOutput(jsonToCsv(parsed)); break;
        default: setOutput(JSON.stringify(parsed, null, 2));
      }
    } catch (e) {
      setError((e as Error).message);
    }
  }, [input, mode]);

  // Converters
  const jsonToTypeScript = (obj: any, name = "Root"): string => {
    const getType = (v: any): string => Array.isArray(v) ? `${getType(v[0])}[]` : typeof v === 'object' && v !== null ? 'object' : typeof v;
    return `interface ${name} {\n` + Object.keys(obj).map(k => `  ${k}: ${getType(obj[k])};`).join('\n') + `\n}`;
  };
  const jsonToGo = (obj: any, name = "AutoGenerated"): string => {
    return `type ${name} struct {\n` + Object.keys(obj).map(k => 
        `\t${k.charAt(0).toUpperCase() + k.slice(1)} ${typeof obj[k] === 'number' ? 'float64' : 'string'} \`json:"${k}"\``
    ).join('\n') + `\n}`;
  };
  const jsonToJava = (obj: any, name = "AutoGenerated"): string => {
      return `public class ${name} {\n` + Object.keys(obj).map(k => 
        `    private ${typeof obj[k] === 'number' ? 'double' : 'String'} ${k};`
      ).join('\n') + `\n    // Getters and Setters omitted\n}`;
  };
  const jsonToXml = (obj: any): string => {
      const toXml = (v: any, name: string): string => {
          if (typeof v !== 'object' || v === null) return `<${name}>${v}</${name}>`;
          return `<${name}>${Object.keys(v).map(k => toXml(v[k], k)).join('')}</${name}>`;
      }
      return `<?xml version="1.0" encoding="UTF-8"?>\n<root>${Object.keys(obj).map(k => toXml(obj[k], k)).join('')}</root>`;
  }
  const jsonToCsv = (obj: any): string => {
      const arr = Array.isArray(obj) ? obj : [obj];
      if (arr.length === 0) return '';
      const headers = Object.keys(arr[0]);
      return [
          headers.join(','),
          ...arr.map((row: any) => headers.map(h => JSON.stringify(row[h] || '')).join(','))
      ].join('\n');
  }

  return (
    <div className="space-y-6 h-[calc(100vh-4rem)] flex flex-col">
      <div>
        <h2 className="text-2xl font-bold text-slate-800 dark:text-white">{t('tool.json.title')}</h2>
        <p className="text-slate-500 dark:text-slate-400">{t('tool.json.desc')}</p>
      </div>

      <div className="flex flex-wrap gap-2 bg-slate-100 dark:bg-slate-800 p-2 rounded-lg border border-slate-200 dark:border-slate-700">
        {[{id: 'format', l: t('tool.json.prettify')}, {id: 'minify', l: t('tool.json.minify')}, {id: 'toTS', l: 'To TS'}, {id: 'toGo', l: 'To Go'},
          {id: 'toJava', l: 'To Java'}, {id: 'toXML', l: 'To XML'}, {id: 'toCSV', l: 'To CSV'}
        ].map((m) => (
          <button key={m.id} onClick={() => setMode(m.id)} className={`px-3 py-1.5 text-xs font-medium rounded-md transition-all ${mode === m.id ? 'bg-blue-600 text-white shadow' : 'text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-white hover:bg-slate-200 dark:hover:bg-slate-700'}`}>{m.l}</button>
        ))}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 flex-1 min-h-0">
        <Card className="flex flex-col h-full">
          <CardHeader title={t('tool.json.input')} action={input && <button onClick={() => { setInput(''); setOutput(''); }} className="text-slate-400 hover:text-red-400"><TrashIcon className="w-4 h-4" /></button>} />
          <div className="flex-1 p-2 bg-slate-50 dark:bg-slate-900">
            <TextArea value={input} onChange={(e) => setInput(e.target.value)} placeholder='{"name": "Azin"}' className="w-full h-full border-0 bg-transparent text-slate-900 dark:text-white resize-none p-2 font-mono text-sm" spellCheck={false} />
          </div>
        </Card>
        <Card className="flex flex-col h-full border-blue-900/30">
          <CardHeader title={error ? t('tool.json.error') : t('tool.json.output')} action={<CopyButton text={output} />} />
          <div className="flex-1 p-0 bg-slate-100 dark:bg-slate-950 overflow-hidden relative">
             {error ? <div className="p-4 text-red-500 dark:text-red-400 font-mono text-sm">{error}</div> : 
             <TextArea readOnly value={output} className="w-full h-full border-0 bg-transparent resize-none p-4 font-mono text-emerald-600 dark:text-emerald-400 text-sm" />}
          </div>
        </Card>
      </div>
    </div>
  );
};

// --- Code Format Tools ---
export const CodeTools: React.FC = () => {
  const [codeInput, setCodeInput] = useState('');
  const [codeLang, setCodeLang] = useState('html');
  const [codeOutput, setCodeOutput] = useState('');
  const { t } = useAppContext();

  useEffect(() => {
      if (!codeInput) { setCodeOutput(''); return; }
      if (codeLang === 'html') {
        setCodeOutput(codeInput.replace(/>\s*</g, ">\n<").replace(/(<[a-zA-Z0-9]+[^>]*>)/g, "$1\n").replace(/(<\/[a-zA-Z0-9]+>)/g, "\n$1"));
      } else if (codeLang === 'sql') {
        setCodeOutput(codeInput.replace(/\b(SELECT|FROM|WHERE|AND|OR|ORDER BY|GROUP BY|INSERT|UPDATE|DELETE)\b/gi, "\n$1"));
      } else if (codeLang === 'css') {
        setCodeOutput(codeInput.replace(/;/g, ";\n  ").replace(/{/g, " {\n  ").replace(/}/g, "\n}\n"));
      } else {
        setCodeOutput(codeInput);
      }
  }, [codeInput, codeLang]);

  return (
    <div className="space-y-6 h-[calc(100vh-4rem)] flex flex-col">
      <div>
        <h2 className="text-2xl font-bold text-slate-800 dark:text-white">{t('tool.code.title')}</h2>
        <p className="text-slate-500 dark:text-slate-400">{t('tool.code.desc')}</p>
      </div>
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 flex-1 min-h-0">
        <Card className="flex flex-col h-full">
          <div className="px-6 py-4 border-b border-slate-200 dark:border-slate-700 bg-slate-50/50 dark:bg-slate-800/50 flex justify-between items-center">
              <h3 className="font-semibold text-slate-800 dark:text-white">{t('tool.code.input')}</h3>
              <div className="w-32"><Select value={codeLang} onChange={(e) => setCodeLang(e.target.value)}><option value="html">HTML</option><option value="sql">SQL</option><option value="css">CSS</option></Select></div>
          </div>
          <TextArea value={codeInput} onChange={(e) => setCodeInput(e.target.value)} className="flex-1 w-full border-0 bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-white p-4 resize-none font-mono text-sm" placeholder={t('tool.code.paste')} spellCheck={false} />
        </Card>
        <Card className="flex flex-col h-full border-blue-900/30">
            <CardHeader title={t('tool.code.output')} action={<CopyButton text={codeOutput} />} />
            <TextArea readOnly value={codeOutput} className="flex-1 w-full border-0 bg-slate-100 dark:bg-slate-950 p-4 resize-none font-mono text-blue-600 dark:text-blue-300 text-sm" />
        </Card>
      </div>
    </div>
  );
};

// --- Encoder Tools ---
export const EncoderTools: React.FC = () => {
  const [encodeInput, setEncodeInput] = useState('');
  const [encodeMode, setEncodeMode] = useState('base64_enc');
  const [encodeOutput, setEncodeOutput] = useState('');
  const { t } = useAppContext();

  const stringToHex = (str: string) => str.split('').map(c => c.charCodeAt(0).toString(16).padStart(2, '0')).join(' ');
  const hexToString = (str: string) => str.replace(/\s/g,'').match(/.{1,2}/g)?.map(byte => String.fromCharCode(parseInt(byte, 16))).join('') || '';

  useEffect(() => {
    if (!encodeInput) { setEncodeOutput(''); return; }
    try {
        let res = '';
        switch(encodeMode) {
            case 'base64_enc': res = btoa(encodeInput); break;
            case 'base64_dec': res = atob(encodeInput); break;
            case 'url_enc': res = encodeURIComponent(encodeInput); break;
            case 'url_dec': res = decodeURIComponent(encodeInput); break;
            case 'hex_bin': res = stringToHex(encodeInput); break;
            case 'bin_hex': res = hexToString(encodeInput); break;
        }
        setEncodeOutput(res);
    } catch(e) { setEncodeOutput("Conversion Error"); }
  }, [encodeInput, encodeMode]);

  return (
    <div className="space-y-6">
       <div>
        <h2 className="text-2xl font-bold text-slate-800 dark:text-white">{t('tool.encoder.title')}</h2>
        <p className="text-slate-500 dark:text-slate-400">{t('tool.encoder.desc')}</p>
      </div>
      <Card>
          <CardContent className="space-y-6 p-6">
               <div className="flex flex-col gap-4">
                   <div className="flex gap-4 items-center">
                       <Label className="mb-0 w-24">{t('tool.encoder.mode')}</Label>
                       <div className="flex-1 flex gap-2 bg-slate-50 dark:bg-slate-900 p-1 rounded-md border border-slate-300 dark:border-slate-700">
                           <select className="w-full bg-transparent text-slate-900 dark:text-white text-sm p-1 outline-none" value={encodeMode} onChange={(e) => setEncodeMode(e.target.value)}>
                               <option value="base64_enc">Base64 Encode</option>
                               <option value="base64_dec">Base64 Decode</option>
                               <option value="url_enc">URL Encode</option>
                               <option value="url_dec">URL Decode</option>
                               <option value="hex_bin">Text to Hex</option>
                               <option value="bin_hex">Hex to Text</option>
                           </select>
                       </div>
                   </div>
                   <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                       <div className="space-y-2">
                           <Label>{t('tool.encoder.input')}</Label>
                           <TextArea value={encodeInput} onChange={(e) => setEncodeInput(e.target.value)} className="h-64 bg-slate-50 dark:bg-slate-900 text-slate-900 dark:text-white" placeholder={t('tool.encoder.type')} />
                       </div>
                       <div className="space-y-2">
                           <Label>{t('tool.encoder.result')}</Label>
                           <div className="relative h-64">
                              <TextArea readOnly value={encodeOutput} className="h-full text-emerald-600 dark:text-emerald-400 bg-slate-100 dark:bg-slate-950 resize-none" />
                              <div className="absolute top-2 right-2"><CopyButton text={encodeOutput} /></div>
                           </div>
                       </div>
                   </div>
              </div>
          </CardContent>
      </Card>
    </div>
  );
};
